# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-23 23:47
from __future__ import unicode_literals

import django.db.models.deletion
import kolibri.plugins.kolibri_hummus.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', kolibri.plugins.kolibri_hummus.models.UUIDField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('sentTime', models.DateTimeField(auto_now_add=True)),
                ('opened', models.BooleanField(default=False)),
                ('file', models.FileField(null=True, upload_to=kolibri.plugins.kolibri_hummus.models.generate_file_path)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessageThread',
            fields=[
                ('id', kolibri.plugins.kolibri_hummus.models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('deleted', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_message_thread', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(help_text=b'Users who are in the message thread', related_name='participated_message_threads', to=settings.AUTH_USER_MODEL, verbose_name=b'participants')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='kolibri_hummus.MessageThread', verbose_name=b'thread'),
        ),
    ]
