# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-24 06:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kolibri_hummus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['sentTime']},
        ),
    ]
